// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-5IrlITkgv3eW6uPViAgIP3c0VIT43KE',
    appId: '1:868375656670:web:7fcdf8c8dc6e6125c66a4f',
    messagingSenderId: '868375656670',
    projectId: 'medical-e6ee2',
    authDomain: 'medical-e6ee2.firebaseapp.com',
    storageBucket: 'medical-e6ee2.firebasestorage.app',
    measurementId: 'G-T6EMQ12CWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUwSGw4kpB4ZLI8fqN1uzrplbXz5Wf4pk',
    appId: '1:868375656670:android:e0f9b0aa9988bf91c66a4f',
    messagingSenderId: '868375656670',
    projectId: 'medical-e6ee2',
    storageBucket: 'medical-e6ee2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDbNRYWMqi7UJQ4up1Jk7A6O3TTUh3yNA',
    appId: '1:868375656670:ios:42bc2e445da95507c66a4f',
    messagingSenderId: '868375656670',
    projectId: 'medical-e6ee2',
    storageBucket: 'medical-e6ee2.firebasestorage.app',
    iosBundleId: 'com.example.shopsmartUsersAr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDbNRYWMqi7UJQ4up1Jk7A6O3TTUh3yNA',
    appId: '1:868375656670:ios:42bc2e445da95507c66a4f',
    messagingSenderId: '868375656670',
    projectId: 'medical-e6ee2',
    storageBucket: 'medical-e6ee2.firebasestorage.app',
    iosBundleId: 'com.example.shopsmartUsersAr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-5IrlITkgv3eW6uPViAgIP3c0VIT43KE',
    appId: '1:868375656670:web:5f78194df7109e2cc66a4f',
    messagingSenderId: '868375656670',
    projectId: 'medical-e6ee2',
    authDomain: 'medical-e6ee2.firebaseapp.com',
    storageBucket: 'medical-e6ee2.firebasestorage.app',
    measurementId: 'G-RM5V7KH2M3',
  );
}
